---

logging:
  level:
    com:
      netflix:
        eureka:OFF
        discovery:OFF

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
    
security:
  user:
    name: Dstashek  
    password: Snoopy123